apiVersion: v1

kind: Pod

metadata:
  name: api
  labels:
    app: api

spec:
  containers:
    - containerName: api
      image: <your-dockerhub-username>/contacts-api:v1
      pullPolicy: always
      port: 8000
      env:
        - name: MONGO_HOST
          value: "mongodb-service"
        - name: MONGO_PORT
          value: "27017"
        - name: MONGO_DB
          value: "contactsdb"